// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBidq8k2GSN1EF-y2tsELYqqOvDmxwU-k',
    appId: '1:345571309953:web:18751c3361b32c0b331080',
    messagingSenderId: '345571309953',
    projectId: 'chatieapp-a9952',
    authDomain: 'chatieapp-a9952.firebaseapp.com',
    storageBucket: 'chatieapp-a9952.appspot.com',
    measurementId: 'G-6BMNEZ0LVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsTwbwmoYv5hIj5Plz86MMoBcciZjldgU',
    appId: '1:345571309953:android:0a4fa4ea26b28f79331080',
    messagingSenderId: '345571309953',
    projectId: 'chatieapp-a9952',
    storageBucket: 'chatieapp-a9952.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4jcP5v-8ybMVb_saqCTc94wBE3wG_J-4',
    appId: '1:345571309953:ios:3a48500deac1e74f331080',
    messagingSenderId: '345571309953',
    projectId: 'chatieapp-a9952',
    storageBucket: 'chatieapp-a9952.appspot.com',
    iosBundleId: 'com.example.chatieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4jcP5v-8ybMVb_saqCTc94wBE3wG_J-4',
    appId: '1:345571309953:ios:3a48500deac1e74f331080',
    messagingSenderId: '345571309953',
    projectId: 'chatieapp-a9952',
    storageBucket: 'chatieapp-a9952.appspot.com',
    iosBundleId: 'com.example.chatieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBidq8k2GSN1EF-y2tsELYqqOvDmxwU-k',
    appId: '1:345571309953:web:339a539086034813331080',
    messagingSenderId: '345571309953',
    projectId: 'chatieapp-a9952',
    authDomain: 'chatieapp-a9952.firebaseapp.com',
    storageBucket: 'chatieapp-a9952.appspot.com',
    measurementId: 'G-4HWXQDTCHX',
  );
}
